In [17]:
import torch
print(torch.__version__)

2.8.0+cpu


## Basics of Tensor

In [18]:
scalar = torch.tensor(7)
scalar  # Has no dimension

tensor(7)

In [19]:
scalar.ndim
scalar.item()  # To get back a normal integer

7

In [20]:
vector = torch.tensor([7,8])
vector  # Has two dimension ( magnitude and direction )

tensor([7, 8])

In [21]:
Matrix = torch.tensor([[7,8] , [4,5]])
Matrix

tensor([[7, 8],
        [4, 5]])

In [22]:
Tensor = torch.tensor([[[1,2,3] , [4,5,6] , [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.3943, 0.0736, 0.3936, 0.5073],
        [0.7237, 0.8233, 0.5836, 0.1182],
        [0.0277, 0.0054, 0.2645, 0.9334]])

In [24]:
random_image_tensors = torch.rand(size=(3,224,224))  # Use to encode an image size = ( rgb , widht , height)
random_image_tensors.shape

torch.Size([3, 224, 224])

In [25]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
zero_to_x = torch.arange(start=1,end=10 ,step= 3)
zero_to_x

tensor([1, 4, 7])

## Tensor data types

In [28]:

tensor_32 =  torch.tensor([3, 4, 5] , 
                              dtype= None,                  # what data type the tensor is ? 
                              device='cpu',                 # to use cpu or cuda , etc
                              requires_grad=False)          # whether to not track gradient of the tensor operations

In [29]:
tensor_16 = tensor_32.type(torch.float16)     # to convert the data type
tensor_16

tensor([3., 4., 5.], dtype=torch.float16)

## Tensor operations

In [30]:
tensor_data = torch.tensor([1,2,3])

In [31]:
print('Add :' , tensor_data + 10)
print('Sub :' , tensor_data - 10)
print('Mul :' , tensor_data * 10)
print('Div :' , tensor_data / 10) 

Add : tensor([11, 12, 13])
Sub : tensor([-9, -8, -7])
Mul : tensor([10, 20, 30])
Div : tensor([0.1000, 0.2000, 0.3000])


## Tensor matrix multiplication

In [32]:
# Scalar multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor1 * tensor2

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
print(torch.matmul(tensor1,tensor2))  # Follows the classic math matirx multipication
print(torch.matmul(torch.rand(3,2) , torch.rand(2,3)))

tensor(14)
tensor([[0.2578, 0.7044, 0.5768],
        [0.2515, 0.7948, 0.7147],
        [0.2404, 0.8437, 0.8017]])


In [34]:
ten = (torch.rand(2,3))
ten


tensor([[0.6317, 0.2928, 0.2835],
        [0.5710, 0.2367, 0.6350]])

In [35]:
ten.T              # to transpose a matrix

tensor([[0.6317, 0.5710],
        [0.2928, 0.2367],
        [0.2835, 0.6350]])

## Tensor Aggregate functions

In [36]:
x = torch.arange(1,11)
print(x.min())
print(x.max())
print(x.sum())
print(x.type(torch.float32).mean())

tensor(1)
tensor(10)
tensor(55)
tensor(5.5000)


In [37]:
print(x.argmax())  # will return the min and max value's position
print(x.argmin())

tensor(9)
tensor(0)


## Tensor Manipulation

" Reshaping - View - Stacking - Squeeze - Unsqueeze - premute " 

In [38]:
import torch
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [39]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)          # Note that , the reshape size should be compatible to the no of exixting elements { 9 elements= 3x3 }
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
# change the view
z = x.view(3,3)
z                  # Changing the view z will change the x also ( because x and z use the same memory)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
# Stacking the tensors
x_stack = torch.stack([x,x,x] , dim=1)
x_stack

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [ ]:
# Squeeze removes the 1-dim elements from the data
x_reshaped = x_reshaped.squeeze().shape    # remove one sq. bracket == one dimensions
x_reshaped                                 # Unsqueese adds a dimension to the target tensor ( dim=1)

torch.Size([3, 3])

In [48]:
# permute , changes the axis of dimension
x = torch.rand(224,224,3)
x_premute = x.permute(2,1,0)
x_premute.shape


torch.Size([3, 224, 224])

## Indexing in tensors

In [53]:
random = torch.arange(1,10)
random = random.reshape(1,3,3)

In [55]:
random[0][0][0]

tensor(1)

In [56]:
random[0 , 2, 2]

tensor(9)

In [57]:
random[0,2, :]

tensor([7, 8, 9])

In [58]:
random[0, : , 2]

tensor([3, 6, 9])